name: Build and Publish

on:
  workflow_run:
    workflows: ["Semantic Release"]
    types:
      - completed

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if new release was created
        id: check-release
        run: |
          # Get the latest tag
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          
          # Get the tag from the previous commit
          previous_tag=$(git describe --tags --abbrev=0 HEAD~1 2>/dev/null || echo "")
          
          if [ "$latest_tag" != "$previous_tag" ] && [ -n "$latest_tag" ]; then
            echo "new_release=true" >> "$GITHUB_OUTPUT"
            echo "New release detected: $latest_tag"
          else
            echo "new_release=false" >> "$GITHUB_OUTPUT"
            echo "No new release detected"
          fi

      - name: Set up Docker Buildx
        if: steps.check-release.outputs.new_release == 'true'
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to registry ${{ env.REGISTRY }}
        if: steps.check-release.outputs.new_release == 'true'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get image name
        if: steps.check-release.outputs.new_release == 'true'
        id: image
        run: |
          LOWERCASE_REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "value=$LOWERCASE_REPO" >> "$GITHUB_OUTPUT"

      - name: Get latest git tag
        if: steps.check-release.outputs.new_release == 'true'
        id: app-version
        run: |
          version=$(git describe --tags --abbrev=0 | sed 's/^v//')
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker image
        if: steps.check-release.outputs.new_release == 'true'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ steps.image.outputs.value }}:latest
            ${{ env.REGISTRY }}/${{ steps.image.outputs.value }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ steps.image.outputs.value }}:${{ steps.app-version.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max